server.port=8083

spring.data.mongodb.uri=${MONGO_URI}

#email configuration
resend.api.key=${API_KEY}
resend.api.url=https://api.resend.com/emails
resend.enabled=${RESEND_ENABLED:true}
resend.mail.from=onboarding@resend.dev
resend.test.email=${TEST_RECIPIENT_EMAIL:}

#application information
app.base.url=http://localhost:8083


#Cloudinary information
cloudinary.cloud-name=drqtj2qgi
cloudinary.api-key=876668743314878
cloudinary.api-secret=66QMtEwAdIpvVV_fvXai9bY9zE4