server.port=8083

spring.data.mongodb.uri=${MONGO_URI}

#email configuration
spring.mail.apikey=${API_KEY}
spring.mail.sandboxdomain=${SANDBOX_DOMAIN}
spring.mail.baseurl=${BASE_URL}
spring.mail.from=adarmy24@gmail.com

#application information
app.base.url=http://localhost:8083
